import { Avatar, UserData, UserMessage } from 'types';

export const users: UserData[] = [
  {
    id: 1,
    name: 'Evelyn Mcfadden',
    status: 'All good',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.a,
    messages: 0,
  },
  {
    id: 2,
    name: 'Amiya Shelton',
    status: 'All good',
    connectedDate: new Date().toJSON(),
    online: false,
    avatar: Avatar.b,
    messages: 123,
  },
  {
    id: 3,
    name: 'Amiya Shelton',
    status: 'All good',
    connectedDate: new Date().toJSON(),
    online: false,
    avatar: Avatar.c,
    messages: 123,
  },
  {
    id: 4,
    name: 'Amiya Shelton',
    status: 'All good',
    connectedDate: new Date().toJSON(),
    online: false,
    avatar: Avatar.d,
    messages: 123,
  },
  {
    id: 5,
    name: 'Amiya Shelton',
    status: 'All good',
    connectedDate: new Date().toJSON(),
    online: false,
    avatar: Avatar.e,
    messages: 123,
  },
  {
    id: 6,
    name: 'Asa Stone Asa Stone Asa Stone Asa Stone Asa Stone ',
    status: 'Am fine  fine  fine  fine  fine  fine  fine ',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.c,
    messages: 12,
  },
  {
    id: 7,
    name: 'Asa Stone Asa Stone Asa Stone Asa Stone Asa Stone ',
    status: 'Am fine  fine  fine  fine  fine  fine  fine ',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.c,
    messages: 12,
  },
  {
    id: 8,
    name: 'Asa Stone Asa Stone Asa Stone Asa Stone Asa Stone ',
    status: 'Am fine  fine  fine  fine  fine  fine  fine ',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.c,
    messages: 12,
  },
  {
    id: 9,
    name: 'Asa Stone Asa Stone Asa Stone Asa Stone Asa Stone ',
    status: 'Am fine  fine  fine  fine  fine  fine  fine ',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.c,
    messages: 12,
  },
  {
    id: 10,
    name: 'Asa Stone Asa Stone Asa Stone Asa Stone Asa Stone ',
    status: 'Am fine  fine  fine  fine  fine  fine  fine ',
    connectedDate: new Date().toJSON(),
    online: true,
    avatar: Avatar.c,
    messages: 12,
  },
];

export const messages: UserMessage[] = [
  {
    id: 0,
    user: users[3],
    me: false,
    text: 'Hey guys',
    date: new Date('1/02/2021').toJSON(),
  },
  {
    id: 1,
    user: users[0],
    me: false,
    text: 'In this month, you will receive 5 new messages',
    date: new Date().toJSON(),
  },
  {
    id: 2,
    user: users[1],
    me: true,
    text: 'My big message to you big message to you big message to you big message to you message to you message to you message to you message to you',
    date: new Date().toJSON(),
    status: 'received',
  },
  {
    id: 3,
    user: users[1],
    me: true,
    text: 'OK',
    date: new Date().toJSON(),
    status: 'sent',
  },
  {
    id: 4,
    user: users[4],
    me: false,
    text: 'In this month, you will receive 5 new messages',
    date: new Date().toJSON(),
  },
];
